AllCops:
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/geohash.rb
    - lib/manager/geo.rb
    - bin/spring
    - bin/setup
    - bin/update
Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - config/puma.rb
    - config/*
  Max: 120
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Documentation:
  Enabled: false
